using System;

namespace ATLAprinter
{
  class Air
  {
    public void printASCIIart()
    {
      Console.WriteLine(@"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0OxolcccodxOKXWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKOxddolc::;;,,''....':lx0XWMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK000OkO0KXXNWWWWWNNXKOkdl:'...:d0WMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXXNWWMMMMMMMMMMMMMMMMMMMMMMWN0d:. .;xXMMMMMM
MMMMMMMMMMMMMMWWNXK0000KKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx;. 'dXMMMM
MMMMMMMMMWKkoc::::::::c:::;:cdOXWMMMMMMMMMMMMMMMMMMMN0xoc::cld0NWMMMMMNk;  ,OWMM
MMMMMMWOl,..;lxOKXNWWWWNXK0xo:,,ckNMMMMMMMMMMMMMMNOc'...,;;'...'ckNMMMMMNx. .dNM
MMMMWO:..;dKWMMMMMMMMMMMMMMMMWXx;.'xNMMMMMMMMMMW0:..:d0XWWWNXKkl'.;OWMMMMWk. .xW
MMMXo..;ONMMMMMMMMWNXXKXNMMMMMMMNx..lNMMMMMMMMNx..c0WMMMMMMMMMMMXl..dNMMMMNc  '0
MM0; .dNMMMMMMW0xxkkxxdlloxXWMMMMWx..oWMMMMMMWk..oNMMMMMMMMMMMMMMWd..xWMMMMx.  o
MK; .xWMMMMMXxllkXWMMMMWXkc;oXMMMMX; '0MMMMMMX:.lNMMMMMWNNWMMMMMMMN: :XMMMMk.  c
Nc  oNMMMMWO;;kNMMMMMMMMMMNl.:XMMMWl .xMMMMMM0''0MMMMWOlokKNWMMMMMNc lNMMMWd   o
k. ,KMMMMWk.'OMMMMMMWNWMMMMk..kMMMWo .xMMMMMMO.,KMMMM0''0MMMMMMMMWk',0MMMMK;  ,0
: .dWMMMMK, oWMMMMMMXxOWMWKl'lXMMMNl '0MMMMMM0,.kMMMM0,.kWMMMMMWKd:lKMMMMNl  .xW
. .OMMMMMx. oWMMMMMMMKxxOOOOKWMMMM0'.oNMMMMMMWd.,0MMMWO:;codxxxxddKWMMMMXc  .kWM
. ,KMMMMM0' ;KMMMMMMMMMWNWMMMMMMMK:.lNMMMMMMMMNo.,OWMMMWX0OOO0KXWMMMMMNk,  :0WMM
, ,KMMMMMWk' ;0WMMMMMMMMMMMMMMMNk,'dNMMMMMMMMMMWk,'lONMMMMMMMMMMMMMWXx;..:kNMMMM
l 'OMMMMMMWKo''cOXWMMMMMMMMMNKd:;l0WMMMMMMMMMMMMMXx:,;lkKXNWWWWNKOo:'.,o0WMMMMMM
O' oWMMMMMMMMXkl;;cldxkkxddollokXWMMMMMMMMMMMMMMMMMWKxlc::::::::;;:lx0NMMMMMMMMM
Wd..kWMMMMMMMMMMNKkxdooddxk0XWMMMWX0kdolcllodkKNMMMMMMMWNXK0OO0KXWWMMMMMMMMMMMMM
MNo..xWMMMMMMMMMMMMMMMMMMMMMMWXOl;..';cloodocc::lxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMNx..oXMMMMMMMMMMMMMMMMMMMW0o'..;d0XWMMMMMMMWNOo;':kNMMMMMMMMMMMMMMMWNWMMMMMMMM
MMMW0:.;0WMMMMMMMMMMMMMMMMXo. .l0WMMMMMMMMMMMMMMMNk,.;kNMMMMMMMMMMMMMXXWMMMMMMMM
MMMMMNk;,oXMMMMMMMMMMMMMMXc  :0WMMMMMWNXKXNWMMMMMMMK: .lXMMMMMMMMMMMMK0WMMMMMMMM
MMMMMMMNkc:dXWMMMMMMMMMMNl  :XMMMMW0o:;:cclclONMMMMMK; .dWMMMMMMMMMMMOOWMMMMMMMM
MMMMMMMMMWKxdkKWMMMMMMMMO. .kMMMMKc.'o0XNNNKo'dWMMMMWd. cNMMMMMMMMMMNxkMMMMMMMMM
MMMMMMMMMMMMNK00XNWMMMMMd. '0MMMXc .xWMMMMMWkckWMMMMMx. lNMMMMMMMMMMOl0MMMMMMMMM
MMMMMMMMMMMMMMMWNNWMMMMMx. .OMMMK, .xMMMMMMNKXMMMMMMWl 'OMMMMMMMMMMXclNMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM0'  oWMMNo  cXMMMMMMMMMMMMMWk''OWMMMMMMMMMXc,OMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWd. 'OWMMNd..c0WMMMMMMMMMWKdcoKMMMMMMMMMMK:.xWMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMXl  ,OWMMWKo;,cox0KKKK0OkkOXWMMMMMMMMMNx'.dNMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNo. .oXWMMMNKkxxxkOO00KNMMMMMMMMMMWKd,.'kWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0:. .l0NMMMMMMMMMMMMMMMMMMMMWXOd:. .lKMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO:. .,lx0XXNWWWWWWNNXKOxdl;.   ,oKWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'. ....,,,,,''...    .';oONMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc::,'......',:cok0NWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNK0000KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
");
    }

    public void ASCIItext()
    {
      Console.WriteLine(@"
                       _                    _          _      
                      / /\                 /\ \       /\ \    
                     / /  \                \ \ \     /  \ \   
                    / / /\ \               /\ \_\   / /\ \ \  
                   / / /\ \ \             / /\/_/  / / /\ \_\ 
                  / / /  \ \ \           / / /    / / /_/ / / 
                 / / /___/ /\ \         / / /    / / /__\/ /  
                / / /_____/ /\ \       / / /    / / /_____/   
               / /_________/\ \ \  ___/ / /__  / / /\ \ \     
              / / /_       __\ \_\/\__\/_/___\/ / /  \ \ \    
              \_\___\     /____/_/\/_________/\/_/    \_\/    
                                                
");
    }
  }
}
