using System;

namespace ATLAprinter
{
  class Fire
  {
    public void printASCIIart()
    {
      Console.WriteLine(@"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx' .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc';. oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:.oXo..OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:.oNMK; ;xKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.:XMMWO' .:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMO..kMMXKNk.  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMKkk0XWMMMMMMMMMMMMMWo ,KMWdlXWOo, 'kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMK:  .:xXWMMMMMMMMMMNc ;KMWo'kMMMXo..:ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMK;   .'l0WMMMMMMMMWo .kMMO',0MMMW0l..,dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMO. ,o:..:ONMMMMMMM0, :XMWx.'kNWMMWKd;..;xXWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc .OW0c..:OWMMMMMWx. cXMWk'.,lKWMMMW0o,..l0WMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMx. oWMW0c..lKMMMMMWd. cXMMKc'..lKWMMMMNk:..lXMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMk. cNMWWWO;.,kWMMMMNo. lNMMWXO:..oXMMMMMWk' ,0MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMd. cNW00WMXo..dNMMMMNc .xMMMMMNd. ,OWMMMMM0; ,KMMMMMMMMMMMMMMMWWWMMM
MMMMMMMMMMMNc .xWM0o0MMWk..oNMMMMO. lNMMMMMWk. '0MMMMMMO' lNMMMMMMMWKOdolc:dXMMM
MMMMMMMMMMWd. cXMMXclNMMWx..xWMMMO..dWMMMMMMWo .dMMMMMMNc '0MMMWXkc,',::. ;0WMMM
MMMMMMMMMNd. :KMMMX:;KMMMNc ,0MMK:.cXMMMMMMMMk. dWMMMMMWo .OMW0l..,lkXXl.,0MMMMM
MMMMMMMMKc..lXMMMMK,,0MMMMx. dNO,.lXMMMMMMMMMx..kMMMMMMNc ,KXo..:ONMMWd..xWMMMMM
MMMMMMNx' ,kWMMMMWx.:XMMMMk. ';.;kWMMMMMMMMMXc cNMMMMMMO'.lk;.;OWWNWMX: '0MMMMMM
MMMMW0:..lXMMMMMM0,.xWMMMMk.  ,xNMMMMMMMMMMXl.,0MMMMMMK:.:o..oNMKx0WMK, ;XMMMMMM
MMMNx' 'kWMMMMMMK;.oNMMMMX:.,xNMMMMNKOxdddo:..,dOXWMMWkcdd..xWM0:oNMMX: ,KMMMMMM
MMNo. ;0WMMMMMW0;.oNMMMWO;'oXMMMNkoloxk00KK00kdc;,;o0NWWK;.dWMNl,0MMMWd..dWMMMMM
MWx. cXMMMMMMWx..dWMMMWx',OWMMXd,'oKWMMMMMMMMMMMNOl'.;xXd.,KMM0,:XMMMMK; 'OWMMMM
M0' ;KMMMMMMWx. oNMMMWk.'OMMW0; 'OWMMMWXK0OO0XWMMMMXd. '. cNMMk.,KMMMMM0, 'OWMMM
Wd..kMMMMMMMK, :XMMMM0, oWMMK; .xWMWKoclolc:,,;oONMMW0;   oWMM0'.dWMMMMMK: .xWMM
Nc '0MMMMMMMx..dWMMMWd..kMMMk. ;XMM0,.oNMMMWXkc..:0MMMK;  lNMMNl '0MMMMMMXl..dWM
X: ,KMMMMMMWd..xMMMMWd..kMMMO. :XMWo .kMMMMMMMWk. :XMMMO. ;XMMMK, ;KMMMMMMNc .OM
Nl .OMMMMMMMx..dWMMMMO. lNMMX: .OMMKo,:odxkXMMMK, :XMMMK; ,KMMMWd..dWMMMMMMk. oW
MO' :XMMMMMM0' :XMMMMNl .kWMM0;.;0WMMNK000XWMMWd.'OWMMMK, cNMMMMk. lWMMMMMMO. oW
MWk'.cXMMMMMNl .xWMMMMXc .kWMMXd,'lkXNWWWWWWNOc,c0WMMMWd.,0MMMMMx..dWMMMMMNc 'OM
MMW0:.,kNMMMMK; 'OWMMMMNo..lKWMMNOo::ccclloooodKWMMMMXo';0MMMMMNc ,0MMMMMXl.'OWM
MMMMNx,.:kNMMM0, 'kWMMMMW0:..l0WMMMWXK0000KXWMMMMMWXkc:xNMMMMMWx..xWMMMXx;'lKMMM
MMMMMMNkc;:okKNKc..lKMMMMMW0l'';lk0XNWMMMMMMWWXKOxddd0NMMMMMMNo.'kWWXOoccdKWMMMM
MMMMMMMMWN0xxkKWNk,.'dXWMMMMWN0dl:;;::ccllloodoodkKWMMMMMMMNk:'lKWW0xdkKWMMMMMMM
MMMMMMMMMMMMMMMMMMNk:.'cxKWMMMMMMWNK0OOkkOO0XNWMMMMMMMMWN0d:;l0WMMMWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWKxc,,:lx0KNWWMMMMMMMMMMMMMMMMWNKkdl::lkXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWN0xl:;;;;:cclooddddoooolccccclokKNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxdoolccccccllodxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
");
    }

    public void ASCIItext()
    {
      Console.WriteLine(@"
                               (                    
                               )\ )                 
                              (()/(  (   (      (   
                               /(_)) )\  )(    ))\  
                              (_))_|((_)(()\  /((_) 
                              | |_   (_) ((_)(_))   
                              | __|  | || '_|/ -_)  
                              |_|    |_||_|  \___|  
                      
");
    }
  }
}
