using System;

namespace ATLAprinter
{
  class Water
  {
    public void printASCIIart()
    {
      Console.WriteLine(@"MMMMMMMMMMMMMMMMMMMMMMMMMMWXOxl;'..           .';cdOKNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWXOdl:,,,,,,,,,,,''''....     ..,cdkKWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWXkl:;;cokOKXNWWWWWWWWNNNNXK0kdc;'.     .,cx0NMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWKd:''cxKNMMMMMMMMMMMMMMMWWN0xdddddoolc;,..    .,oONMMMMMMMMMMMMMM
MMMMMMMMMMMWXx:. .lKWMMMMMMMMMMMMMMMWKkdoodx0XNWWMMMMWWNX0ko;.   ,o0WMMMMMMMMMMM
MMMMMMMMMW0l;;,.,OWMWKOkkxxOKWMMMMW0dox0XNMMMMMMMMMMMMMMMMMMWXkl,. .:ONMMMMMMMMM
MMMMMMMW0l;lOd.;KWXkxkO00Oxl;:xNMKdoONMMMMMMMMMMMMMMMMMMMMMMMMMMN0o,..;OWMMMMMMM
MMMMMMKl,l0WO''OWO;:KMMMMMMWKc.:dcxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc..c0WMMMMM
MMMMNx,;OWMWo :XK;.dMMMNKNMMMX: 'kWMMMMWWNKOO0XNMMMMMMMMMMMMMMMMMMMMMWKl..dNMMMM
MMMXl'lXMMMWl ;XXc :KMWk:xWMMNc.oWMMW0dllllccc;;cxXWMMMMMNK0kxddddxxOKNNO,.cXMMM
MMK:.dNMMMMM0,.dNXo;:ooldXMMWk.'0MMKc;dKXNWWWWXkc.'dNWKxodxkkO0OOOxdoc::ll' :KMM
MK:.xWMMMMMMWKc':xXNXKXWMMW0d, :XMX:,OWMMMMMMMMMW0;.;c:oONMMMMMMMMMMMWKkc,.  :XM
Nl.dWMMMMMMMMMW0l;:lodxkkkkxOx':NM0,lWMMMWKkKWMMMMO' :0WMMMMMMMMMMMMMMMMMXx,  lN
k.:XNX0OkxxxxxkO000OkkkO0XWMMX:,0MNo:0WMMWx.'OMMMNl'oNMMMMMMMMMMMMMMMMMMMMMXl..x
; 'ccccclloollc::;;:ldOXWMMMMWk'cNMXo;codl,'oXMMWd.lNMMMMMN0kxxdoooxOXMMMMMMNl ,
..d0XNWMMMMMMMMWNXOxl:,,;lxKWMWk;c0WW0dlllxKWMMM0,,0MMMMNkdkOKXXK0Odc:lKWMMMMO'.
 cNMMMMMMMMMMMMMMMMMMWXOd:'.;d0NKo::ok0XXNNXX0ko, :XMMMXccKMMMMMMMMMNx.'kWMMMN:.
 cNWWWWWWWMMMMMMMMMMMMMMMWXx:..,o0Kkolcllllloooxo.;XMMMO.:NMMMMMMMMMMWo.,0MMMWl.
 .clllloooooodkKNWMMMMMMMMMMWXx:..:ONMWNNNNWWMMMX;.xWMMXc.cOKKOx0MMMMMx..OMMMWl.
 'xKXXXXXK0OxolcccoOXWMMMMMMMMMW0o'.;xXWMMMMMMMMWk..kWMMNx;,,,,:0MMMMNl.cNMMMNc.
.'0MMMMMMMMMMMMNKko::cxKWMMMMMMMMMXk:.'ok0WMMMMMMWx'.lKWMMWXKKXWMMMMNo'cKMMMMK;.
,.dWMMMMMMMMMMMMMMMW0dc;cxKWMMMMMMMMW0c...:kNMMMMMWXd;,lkKNWMMMMWNKkllkNMMMMWx.'
d.,0MMMMMMMMMMMMMMMMMMWKx:;ckXMMMMMMMMWKkd;.,o0WMMMMMNOoc:cclodddddx0WMMMMN0o..o
X; ;dxxkO0XNWMMMMMMMMMMMMW0o;;o0WMMMMMMMMMN0o;,;oOXWMMMMWNKOkO0KXWMMMMNKklc;. :X
MO' .cdddooolodOXWMMMMMMMMMMNkc;:xXWMMMMMMMMMWKxc;,;ldk0XNNNWWNNXKOxolccldOd.,0M
MWO'.lXMMMWNKkoc:coONMMMMMMMMMWKd:,cONMMMMMMMMMMWN0xoc::cccccllccclodOKNWWx',0MM
MMWO,.cXMMMMMMMWKxc,,ckNMMMMMMMMMNOl;;o0XWMMMMMMMMMMMMWWNXXXXXXXNWMMMMMW0c.:KMMM
MMMMKc.;OWMMMMMMMMWXk:',o0WMMMMMMMMWXxc;;:oONMMMMMMMMMMMMMMMMMMMMMMMMW0c..oXMMMM
MMMMMNx'.lKWMMMMMMMMMWKo,.;xXMMMMMMMMMWX0kl::cx0NWMMMMMMMMMMMMMMMMWKx:. ,OWMMMMM
MMMMMMWKo''oKWMMMMMMMMMMNk:.'oKWMMMMMMMMMMMN0dc;;cldk0KXNNNXXK0kdol:. 'dXMMMMMMM
MMMMMMMMWKl''cONMMMMMMMMMMW0l''ckNMMMMMMMMMMMMWN0kdlllllcclllloodo:,;dXMMMMMMMMM
MMMMMMMMMMWKd,.,o0NMMMMMMMMMWXx;.,o0WMMMMMMMMMMMMMMMMWWNNNNNWWXkc;ckNMMMMMMMMMMM
MMMMMMMMMMMMMNOl,.;oONMMMMMMMMMW0o;,:oOXWWMMMMMMMMMMMMMMMWN0dl:cxKWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMN0d:;;cdOKNWMMMMMMWKkollllodxO0KXXXXXKOxoc:clkKWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWXOdl:::cldxO0KXNNWNXK0kdlc:;'..',;:cokKWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWX0kxdollllooooooooooooolodk0XWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXKKK0KKXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
");
    }

    public void ASCIItext()
    {
      Console.WriteLine(@"
                  .-.  .-.  .--.  _______ ,---.  ,---.    
                  | |/\| | / /\ \|__   __|| .-'  | .-.\   
                  | /  \ |/ /__\ \ )| |   | `-.  | `-'/   
                  |  /\  ||  __  |(_) |   | .-'  |   (    
                  |(/  \ || |  |)|  | |   |  `--.| |\ \   
                  (_)   \||_|  (_)  `-'   /( __.'|_| \)\  
                                         (__)        (__) 
");
    }
  }
}
